export { default as Header } from "./Header/Header";
export {default as Profiles} from './Profiles/Profiles';
export {default as Feature} from "./Feature/Feature";
export {default as Form} from "./Form/Form";
export { default as Jumbotron } from "./Jumbotron/Jumbotron";
export { default as Accordion } from "./Accordion/Accordion";
export { default as GetStartedForm } from "./GetStartedForm/GetStartedForm";
export {default as Loading} from "./Loading/Loading";
export {default as Card} from "./Card/Card";
export { default as Footer } from "./Footer/Footer";
